docker-compose-yaml: docker-compose.yml

project: 'baseimage-example'

tasks:
  post-rollout:
    - run:
        name: Install Drupal if necessary
        command: |
          if [[ ! -f /app/web/sites/default/files/.drupal-installed-derived ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
            drush si minimal -y --existing-config --account-name "${DRUPAL_ADMIN_USER:-admin}" --account-pass "${DRUPAL_ADMIN_PASSWORD:-admin}"
            # Create marker file to indicate successful installation
            touch /app/web/sites/default/files/.drupal-installed-derived
          fi
        service: cli
    # - run:
    #     name: Run Drupal deploy tasks
    #     # Source before https://github.com/uselagoon/lagoon/issues/574
    #     command: source /home/.bashrc && drush -y deploy
    #     service: cli

cronjobs:
  - name: drush cron
    schedule: '*/30 * * * *'
    command: drush cron
    service: cli