FROM ghcr.io/amazeelabs/private-gpt/php:latest


ARG LAGOON_ENVIRONMENT
ARG LAGOON_PROJECT
ARG LAGOON_KUBERNETES
ENV CHAINLIT_URL=https://chat.${LAGOON_ENVIRONMENT}.${LAGOON_PROJECT}.${LAGOON_KUBERNETES}
ENV DRUPAL_URL=https://nginx.${LAGOON_ENVIRONMENT}.${LAGOON_PROJECT}.${LAGOON_KUBERNETES}